# Generated by Django 5.1.7 on 2025-03-25 09:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_daraja'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='malumot',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='body',
            field=models.TextField(),
        ),
    ]
