# Generated by Django 5.1.7 on 2025-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizHaqimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
