# Generated by Django 5.1.7 on 2025-03-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsite', '0002_bizhaqimizda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizhaqimizda',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
